import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect, useState } from "react";
import { Button, Container, Row } from "react-bootstrap";
import { useWeb3React } from "@web3-react/core";
import Header from "../components/Header/Header";
import NFTimage from "../components/NFTimage/NFTimage";
import ConnectWallet from "../components/ConnectWallet/ConnectWallet";
import contractABI from "../WalletHelpers/contractAbi.json";
import Web3 from "web3";
import Minter from "../components/Minter/Minter";

import Map from "../components/Map/Map";

const Home: NextPage = () => {
  const { account, library } = useWeb3React();
  const [number, setNumber] = useState<number>(1);
  const [unitPrice, setUnitPrice] = useState<number>(0.12);
  const [totalSupply, setTotalSupply] = useState<number>(0);
  const [isPublicSaleActive, setIsPublicSaleActive] = useState<boolean>(false);
  // TODO: change this for mainnet values
  const contractAddress = "0xE1A25F378dbbBA97d48b35acbef440b1339aDaE7";
  const provider =
    "https://mainnet.infura.io/v3/84842078b09946638c03157f83405213";
  //
  const web3 = new Web3(provider);
  const contract = new web3.eth.Contract(contractABI as any, contractAddress);

  useEffect(() => {
    (async () => {
      setIsPublicSaleActive(await contract.methods.isPublicSaleActive().call());

      const price = await contract.methods.NFTPrice().call();
      const ethPrice = web3.utils.fromWei(price, "ether");
      setUnitPrice(+ethPrice);
      setTotalSupply(await contract.methods.totalSupply().call());
    })();
  }, []);

  return (
    <section className={styles.section}>
      <Head>
        <title>Apinator 2042</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className={styles.container}>
        <div className={styles.main}>
          <Row>
            <Header />

            <Row className="d-flex flex-column mb-5">
              <ConnectWallet />
            </Row>

            <Map />
          </Row>
          {/* <Row className={styles.buttonGroup}>
            {" "}
            <>
              <Button
                className={styles.button}
                style={{
                  transform: number === 1 ? 'translate3d(10px, 2px, 0) scale(1.1)' : '',
                  backgroundPosition: number === 1 ? '-100% 0' : '',
                  color: number === 1 ? 'black' : ''
                }}
                onClick={() => setNumber(1)}
                variant="dark"
              >
                1
              </Button>
              <Button
                className={styles.button}
                style={{
                  transform: number === 2 ? 'translate3d(10px, 2px, 0) scale(1.1)' : '',
                  backgroundPosition: number === 2 ? '-100% 0' : '',
                  color: number === 2 ? 'black' : ''
                }}
                onClick={() => setNumber(2)}
                variant="dark"
              >
                2
              </Button>
            </>{" "}
          </Row> */}

          <Row className="d-flex flex-column mt-1 mb-1">
            {/* <NFTimage
              nftQuantity={number}
              unitPrice={unitPrice}
              supply={totalSupply}
            /> */}
          </Row>

          {/* <Row className="d-flex flex-column mb-5">
            {!!account && !!library && !isPublicSaleActive && (
              <Minter nftQuantity={number} />
            )}
            {isPublicSaleActive && (
              <div className={styles.success}>PRESALE IS OVER</div>
            )}
          </Row> */}
        </div>
      </Container>
    </section>
  );
};

export default Home;
