name: 1-minute-cron
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://apinators-2042-dusky.vercel.app/api/map?x=-1&y=0&range=3' \
